### ISSUE TITLE
Clarification of the role of GeoPressureViz

### ISSUE THREAD

**Issue by Rafnuss** [Rafnuss/GeoPressureManual#2]
Comment from @grhyne:

> Looking for clarification about geopressureviz: Do changes in this app, like changing a stationary location, directly change anything in the static timeseries in R when I “query pressure”? Or is it simply a visualization tool that I reference to change labels in TRAINSET? I do not see any changes after I query. I am able to do everything I want to in geopressureviz according to the online manual, but it is not clear as to how those changes are integrated back into our data. CB606, for example, has a migratory stopover point that is located in South America, where it should realistically be placed in Florida (where there is some pressure probability). Am I able to implement that location change into the analysis, or simply have to change it’s labelled status in TRAINSET?

**Comment by Rafnuss** [comment]
Should it be included as a seperate chapter? appendix?

**Comment by grhyne** [comment]
@Rafnuss I think that is a good choice, just like TRAINSET gets an appendix, you are right that geopressureviz should as well
